export const DRINK_SAYINGS = [
  "Bottoms up, you beautiful disaster.",
  "Drink like your ex is watching.",
  "Chug it, you absolute donkey.",
  "That's what you get for being a smartass.",
  "Cry about it, then drink about it.",
  "Karma's a bitch and so are you.",
  "Drink up, buttercup.",
  "You built different — differently stupid.",
  "That one's on you, dumbass.",
  "Skol, you glorious idiot.",
  "Drink it before you embarrass yourself further.",
  "Guzzle it like your dignity already left.",
  "That's a you problem now. Drink.",
  "Down the hatch, you menace.",
  "Take the L and take the shot.",
  "Nobody's proud of you right now. Drink.",
  "You absolute clown, bottoms up.",
  "Drink it, you human red flag.",
  "That was rough to watch. Drink it off.",
  "Big oof energy. Drink.",
  "Sip that shame away.",
  "You did that to yourself. Drink.",
  "Drink like you mean it, for once.",
  "That's what happens to fools. Drink.",
  "Congrats on the L, now chug.",
  "Drink it, hot mess express.",
  "That's a whole personality flaw. Drink.",
  "You're this close to being cut off. Drink anyway.",
  "Drink it before someone films this.",
  "Zero shame left, so drink freely.",
  "Somewhere, your mother is disappointed. Drink.",
  "That's rookie numbers. Drink up, amateur.",
  "You absolute walking liability, chug it.",
  "Drink it, you gremlin.",
  "This is why you weren't invited last time. Drink.",
  "Slam it like your reputation.",
  "You had one job. Drink your penalty.",
  "That's a hard pass on being a winner tonight. Drink.",
  "Down it, you feral raccoon in a hoodie.",
  "Drink it, walking red flag parade.",
  "You've officially lost the respect of the table. Drink.",
  "That was a certified yikes. Chug it.",
  "Drink it before your luck gets worse.",
  "You absolute dumpster fire, bottoms up.",
  "That's what happens when you play with confidence you don't have. Drink.",
  "Drink it, disgraced gremlin.",
  "You just lost, and everyone saw it. Drink.",
  "That's a big fat L. Chug accordingly.",
  "Drink it, you unhinged little goblin.",
  "Nobody warned you, so drink now.",
  "You brought this on yourself, champ. Drink.",
  "Drink it like your Wi-Fi depends on it.",
  "That's what happens to cocky idiots. Chug.",
  "Down it, you human disaster zone.",
  "Drink it, you absolute jabroni.",
  "You just got cooked. Drink the evidence away.",
  "That's the sound of your ego popping. Drink.",
  "Drink it, you overconfident buffoon.",
  "Someone tell your therapist. Drink first though.",
  "You lost to a deck of cards. Drink in shame.",
  "Chug it, professional disappointment.",
  "Drink it, you feral little weasel.",
  "That's what happens when karma's got jokes. Drink.",
  "You just got humbled. Take the drink like a grown-up.",
  "Drink it, you certified goblin mode menace.",
  "Nobody's coming to save you. Drink.",
  "That was pathetic, honestly. Drink it off.",
  "Down it, you absolute walking punchline.",
  "Drink it, you chaos gremlin.",
  "You just proved everyone right about you. Drink.",
  "That's the sound of your pride shattering. Chug.",
  "Drink it, you unbothered disaster.",
  "You lost fair and square, dummy. Drink.",
  "Chug it before your excuses get worse.",
  "Drink it, you absolute weapon of self-sabotage.",
  "That's a rough one. Drink it and reflect on your choices.",
  "You just got dragged by a deck of cards. Drink.",
  "Down it, you unlucky little gremlin.",
  "Drink it, you certified mess.",
  "Nobody's surprised. Drink up.",
  "That's what happens when you talk trash. Chug.",
  "Drink it, you feral little menace.",
  "You just embarrassed yourself in front of everyone. Drink.",
  "Chug it, professional screwup.",
  "Drink it, you human oopsie.",
  "That's what confidence without skill gets you. Drink.",
  "Down it, you walking cautionary tale.",
  "Drink it, you overhyped disaster.",
  "You just lost to math. Drink in humility.",
  "Chug it, you absolute clown car.",
  "Drink it, you unlucky little gremlin king.",
  "That was ugly. Drink it off quick.",
  "You just got exposed. Drink the truth away.",
  "Down it, you certified mess of a human.",
  "Drink it, you chaotic little goblin.",
  "Nobody's clapping for you. Drink.",
  "That's what happens when the cards hate you. Chug.",
  "Drink it, you feral disaster.",
  "You just got wrecked. Take it like a champ and drink.",
  "Chug it, you absolute donkey show.",
  "Drink it, you walking L.",
  "That's rough, buddy. Drink it and move on.",
  "Down it, you certified goober.",
  "Drink it, you disaster on two legs.",
  "You just lost to a horizontal card, genius. Drink.",
  "Chug it, professional trainwreck.",
  "Drink it, you human facepalm.",
  "That's what happens to cocky people. Drink up.",
  "Down it, you unbothered mess.",
  "Drink it, you certified goblin.",
  "Nobody's impressed. Drink.",
  "That's what happens when you underestimate a deck of cards. Chug.",
  "Drink it, you feral little donkey.",
  "You just got humbled by a card game. Drink.",
  "Chug it, professional disaster area.",
  "Drink it, you walking red flag festival.",
  "That's rough. Drink it and pray for better luck.",
  "Down it, you certified oopsie daisy.",
  "Drink it, you disaster waiting to happen.",
  "You just proved you can't be trusted with a guess. Drink.",
  "Chug it, you absolute weapon of chaos.",
  "Drink it, you human blooper reel.",
  "That's what happens when confidence exceeds skill. Drink up.",
  "Down it, you unbothered goblin.",
  "Drink it, you certified menace to society.",
  "Nobody's surprised you lost. Drink.",
  "That's what happens when the universe hates you tonight. Chug.",
  "Drink it, you feral little disaster.",
  "You just got cooked by a playing card. Drink.",
  "Chug it, professional embarrassment.",
  "Drink it, you walking cautionary tale.",
  "That's rough, my dude. Drink it off.",
  "Down it, you certified clown.",
  "Drink it, you disaster of a decision maker.",
  "You just lost, and it was ugly. Drink.",
  "Chug it, you absolute weapon of self-destruction.",
  "Drink it, you human oof.",
  "That's what happens when you talk big and play small. Drink.",
  "Down it, you unbothered clown.",
  "Drink it, you certified goblin menace.",
  "Nobody's clapping. Drink and sit down.",
  "That's what happens when the cards call your bluff. Chug.",
  "Drink it, you feral little weapon.",
  "You just got exposed by math. Drink.",
  "Chug it, professional letdown.",
  "Drink it, you walking disaster movie.",
  "That's rough, champ. Drink it and reflect.",
  "Down it, you certified goober king.",
  "Drink it, you disaster in human form.",
  "You just lost to a stack of cards, legend. Drink.",
  "Chug it, you absolute weapon of bad decisions.",
  "Drink it, you human blunder.",
  "That's what happens when luck says no. Drink up.",
  "Down it, you unbothered disaster zone.",
  "Drink it, you certified goblin overlord.",
  "Nobody's surprised, honestly. Drink.",
  "That's what happens when you tempt fate. Chug.",
  "Drink it, you feral little clown.",
  "You just got dragged, and everyone saw it. Drink.",
  "Chug it, professional chaos agent.",
  "Drink it, you walking punchline factory.",
  "That's rough, pal. Drink it and try again.",
  "Down it, you certified oops champion.",
  "Drink it, you disaster with a smile.",
  "You just lost to a rectangle with numbers on it. Drink.",
  "Chug it, you absolute weapon of poor timing.",
  "Drink it, you human whoopsie.",
  "That's what happens when you gamble on vibes. Drink up.",
  "Down it, you unbothered chaos gremlin.",
  "Drink it, you certified disaster royalty.",
  "Nobody's clapping for that. Drink.",
  "That's what happens when the deck fights back. Chug.",
  "Drink it, you feral little oopsie.",
  "You just got humbled, and it was beautiful. Drink.",
  "Chug it, professional walking L.",
  "Drink it, you disaster with main character energy.",
  "That's rough, friend. Drink it and laugh at yourself.",
  "Down it, you certified goblin in training.",
  "Drink it, you disaster of epic proportions.",
  "You just lost, and the cards are laughing. Drink.",
  "Chug it, you absolute weapon of terrible luck.",
  "Drink it, you human trainwreck deluxe.",
  "That's what happens when you play with fire. Drink up.",
  "Down it, you unbothered disaster champion.",
  "Drink it, you certified menace with a heart.",
  "Nobody's surprised, sweetheart. Drink.",
  "That's what happens when the odds catch up. Chug.",
  "Drink it, you feral little chaos gremlin.",
  "You just got roasted by a card game. Drink.",
  "Chug it, professional bad-decision maker.",
  "Drink it, you walking disaster with style.",
  "That's rough, superstar. Drink it and reset.",
  "Down it, you certified goblin champion.",
  "Drink it, you disaster with a great personality.",
  "You just lost to the universe's sense of humor. Drink.",
  "Chug it, you absolute weapon of hilarious failure.",
  "Drink it, you human cautionary tale deluxe.",
  "That's what happens when confidence writes checks skill can't cash. Drink.",
  "Down it, you unbothered legend of bad luck.",
  "That's a full-circle moment of embarrassment. Drink.",
];

export function randomSaying(): string {
  return DRINK_SAYINGS[Math.floor(Math.random() * DRINK_SAYINGS.length)];
}
